version: '3.8'
services:
  spark:
    image: jdvelasq/spark:3.1.3
    container_name: spark
    ports:
      - "4040:4040"
      - "50070:50070"
      - "8088:8088"
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
    command: ["/bin/bash", "-c", "pip install geopandas && /bin/bash"]

  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop
    ports:
      - "50070:50070"
      - "9000:9000"
    volumes:
      - ./hdfs:/hdfs
    command: ["/etc/bootstrap.sh", "-bash"]

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
